### ISSUE TITLE
If shelve extension is not enabled and vc-hgcmd-dir-show-shelve is t, error

### ISSUE THREAD

**Issue by jojojames** [muffinmad/emacs-vc-hgcmd#2]
Set vc-hgcmd-dir-show-shelve to t and either set up mercurial fresh (or disable shelve extension).

````
(defun vc-hgcmd-shelve-list ()
  "Return shelve list."
  (let ((shelves (vc-hgcmd-command "shelve" "-l" "-q")))
    (when shelves (split-string shelves "\n"))))
```

Will error out when trying to run that command.

**Comment by muffinmad** [comment]
Thanks for report!

Shelve extension is now enabled by default via `vc-hgcmd-cmdserver-config-options`.
And `vc-hgcmd-dir-show-shelve` is on by default.

**Comment by jojojames** [comment]
Awesome, thanks and thanks for the package!
