### ISSUE TITLE
vc-annotate-show-changeset-diff-revision-at-line gets stuck

### ISSUE THREAD

**Issue by binki** [muffinmad/emacs-vc-hgcmd#3]
If I annotate a file and then press `D` which calls `vc-annotate-show-changeset-diff-revision-at-line`, the command hangs.

I am running vc-hgcmd-1.12 and Mercurial 5.0.2 (installed via TortoiseHg) on Windows in Emacs 26.3.

**Comment by muffinmad** [comment]
Does this happens for every changeset or for particular one?

Once command hangs, press `C-g` until Emacs become responsive again, then switch to buffer named like ` *hgcmd process: <project-name>*` (note leading space). This buffer is used to communicate with `hg` process. If there are any data, this means data parsing error occurred.

**Comment by binki** [comment]
I upgraded to Emacs-27.1 and I don’t see the issue currently where I was seeing it before. I wonder if it was because the file has spaces in its path (but I can no longer test that)?

Thanks for the debugging suggestion. Since I can’t easily reproduce this at the moment, I will close this issue for now and open another one if I see any issues.

Thanks for the response!
